services:
  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    ports:
      - "8000:8000"
    volumes:
      - "./config:/home/node/app/config"
      - "./data:/home/node/app/data"
      - "./plugins:/home/node/app/plugins"
      - "./extensions:/home/node/app/public/scripts/extensions/third-party"
    restart: unless-stopped
  caddy:
    image: caddy
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    ports:
      - "4430:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
